### ISSUE TITLE
Tried to open the PHP file on the root and got errors

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS-JSON#2]
Warning: require_once(/home/pablo/GitHub/templates/_functions.php): failed to open stream: No such file or directory in /home/pablo/GitHub/specifications-ITS-JSON/index.php on line 3

Fatal error: require_once(): Failed opening required '/home/pablo/GitHub/templates/_functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/pablo/GitHub/specifications-ITS-JSON/index.php on line 3

**Comment by sebastian-iancu** [comment]
These files are not useful for json validation; they are used by openEHR specification website for navigation purposes between classes - see https://specifications.openehr.org/releases/ITS-JSON/latest/components/

**Comment by ppazos** [comment]
@sebastian-iancu which PHP file should be open to get that view?

The issue I see with this is everyone downloading the schemas will get also those PHP, and if those can't be opened, I'm not sure of that is correct to provide them as part of the schema files. Maybe putting them in a separate folder would be better.

**Comment by sebastian-iancu** [comment]
The php file you are asking is not part of this repo, it is part of the specification website. The only purpose to have this php file inhere is to be able to have a user-friendly navigation and file-listing of this repo on the specification website (link provided above).
Why would anyone need these php files?
I would like not have them - but as there is not yet another workable solution, this is the way it is. If you have another solution please let's discuss it with Thomas.

This issue is not a schema issue, that's the reason I closed it before.
